---
sidebar: sidebar 
permalink: install-setup/cable-hardware.html 
keywords: asa r2, aff a1k, aff a70, aff a90, aff c80, asa a1k, asa a90, asa a70, asa a30, asa a20, asa a50, asa c30 cable controllers 
summary: 클러스터 통신, 호스트 네트워크 액세스, 관리 연결 및 스토리지 쉘프 연결을 활성화하려면 ASA r2 스토리지 시스템을 케이블로 연결하십시오. 
---
= ASA R2 스토리지 시스템용 하드웨어를 케이블로 연결합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터 통신, 호스트 네트워크 액세스, 관리 연결 및 스토리지 쉘프 연결을 활성화하려면 ASA r2 스토리지 시스템을 케이블로 연결하십시오.



== 하드웨어 케이블링 개요

각 ASA r2 모델은 슬롯 위치, 포트 할당 및 I/O 모듈 구성이 고유하므로 케이블 연결 방법은 플랫폼 모델별로 다릅니다. 사용 중인 ASA r2 모델에 맞는 절차를 선택하십시오.

* link:cable-hardware-a1k.html["케이블 ASA A1K"]
* link:cable-hardware-a70-90.html["케이블 ASA A70 및 A90"]
* link:cable-hardware-a20-30-50.html["케이블 ASA A20, A30 및 A50"]
* link:cable-hardware-c30.html["케이블 ASA C30"]


하드웨어 케이블 연결 중에 네 가지 유형의 연결을 케이블로 연결합니다.

* *클러스터/HA 연결*
+
두 컨트롤러를 서로 연결하거나(스위치가 없는 클러스터) 클러스터 네트워크 스위치에 연결합니다(스위치형 클러스터). 이러한 연결을 통해 컨트롤러 쌍 간의 클러스터 통신 및 고가용성 페일오버가 가능해집니다. 클러스터 인터커넥트 트래픽과 HA 트래픽은 동일한 물리적 포트를 공유합니다.

* *호스트 네트워크 연결*
+
호스트 구성에 따라 이더넷(iSCSI, NVMe/TCP) 또는 파이버 채널(FC, NVMe/FC)을 사용하여 컨트롤러를 SAN 호스트에 연결합니다. 이러한 연결을 통해 스토리지 워크로드에 대한 데이터 액세스가 제공됩니다.

* *관리 네트워크 연결*
+
ONTAP System Manager 및 CLI를 통해 시스템 관리 액세스가 가능하도록 컨트롤러를 관리 네트워크에 연결하십시오.

* *스토리지 쉘프 연결*
+
컨트롤러를 NS224 스토리지 셸프에 연결하여 시스템에 스토리지 용량을 제공하십시오.





== 추가 리소스

케이블 연결 절차는 일반적인 구성을 보여줍니다. 구체적인 케이블 연결은 스토리지 시스템에 주문한 구성 요소에 따라 다릅니다. 포괄적인 구성 및 슬롯 우선순위 세부 정보는 link:https://hwu.netapp.com["NetApp Hardware Universe를 참조하십시오"^]을 참조하십시오.
