---
sidebar: sidebar 
permalink: install-setup/initialize-ontap-cluster.html 
keywords: asa r2, asa a1k, asa a70, asa a90, initialize cluster, set up cluster, ontap 
summary: System Manager를 사용하여 ASA R2 시스템에서 ONTAP 클러스터를 설정하는 방법에 대해 알아보십시오. 
searchtitle: ONTAP System Manager | ASA R2를 사용하여 ONTAP 클러스터를 설정합니다 
---
= ASA R2 스토리지 시스템에서 ONTAP 클러스터를 설정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager는 ONTAP ASA R2 클러스터를 설정하는 빠르고 쉬운 워크플로를 안내합니다.

클러스터 설정 중에 기본 데이터 스토리지 가상 머신(VM)이 생성됩니다. 필요에 따라 DNS(Domain Name System)를 설정하여 호스트 이름을 확인하고, 클러스터가 시간 동기화에 NTP(Network Time Protocol)를 사용하도록 설정하고, 저장된 데이터의 암호화를 사용하도록 설정할 수 있습니다.

.시작하기 전에
다음 정보를 수집합니다.

* 클러스터 관리 IP 주소입니다
+
클러스터 관리 IP 주소는 클러스터 관리자가 관리 스토리지 VM에 액세스하고 클러스터를 관리하는 데 사용하는 클러스터 관리 인터페이스에 대한 고유한 IPv4 주소입니다. 조직의 IP 주소 할당 담당자로부터 이 IP 주소를 얻을 수 있습니다.

* 네트워크 서브넷 마스크
+
클러스터 설정 중에 ONTAP은 해당 구성에 적합한 네트워크 인터페이스 세트를 권장합니다. 필요한 경우 권장 사항을 조정할 수 있습니다.

* 네트워크 게이트웨이 IP 주소입니다
* 파트너 노드 IP 주소입니다
* DNS 도메인 이름입니다
* DNS 이름 서버 IP 주소입니다
* NTP 서버 IP 주소입니다
* 데이터 서브넷 마스크


.단계
. 클러스터 네트워크를 검색합니다
+
.. 랩톱을 관리 스위치에 연결하고 네트워크 컴퓨터 및 장치에 액세스합니다.
.. 파일 탐색기를 엽니다.
.. 네트워크 * 를 선택한 다음 마우스 오른쪽 버튼을 클릭하고 * 새로 고침 * 을 선택합니다.
.. ONTAP 아이콘 중 하나를 선택한 다음 화면에 표시된 인증서를 수락합니다.
+
System Manager가 열립니다.



. 암호 * 에서 관리자 계정에 대한 강력한 암호를 만듭니다.
+
암호는 8자 이상이어야 하며 문자와 숫자를 하나 이상 포함해야 합니다.

. 암호를 다시 입력하여 확인한 후 * Continue * 를 선택합니다.
. 네트워크 주소 * 에 스토리지 시스템 이름을 입력하거나 기본 이름을 그대로 사용합니다.
+
기본 스토리지 시스템 이름을 변경하는 경우 새 이름은 문자로 시작해야 하며 44자 미만이어야 합니다. 이름에 마침표(.), 하이픈(-) 또는 밑줄(_)을 사용할 수 있습니다.

. 파트너 노드의 클러스터 관리 IP 주소, 서브넷 마스크, 게이트웨이 IP 주소 및 IP 주소를 입력한 다음 * Continue * 를 선택합니다.
. 네트워크 서비스 * 에서 * 호스트 이름을 확인하기 위해 도메인 이름 시스템(DNS)을 사용하고 * 네트워크 시간 프로토콜(NTP)을 사용하여 시간을 동기화하려면 * 원하는 옵션을 선택합니다.
+
DNS를 사용하도록 선택한 경우 DNS 도메인 및 이름 서버를 입력합니다. NTP를 사용하도록 선택한 경우 NTP 서버를 입력한 다음 * 계속 * 을 선택합니다.

. Encryption * 에 Onboard Key Manager(OKM)에 대한 암호를 입력합니다.
+
기본적으로 Onboard Key Manager(OKM)를 사용하여 유휴 데이터 암호화가 선택됩니다. 외부 키 관리자를 사용하려면 선택 사항을 업데이트합니다.

+
선택적으로 클러스터 설정이 완료된 후 암호화에 대해 클러스터를 구성할 수 있습니다.

. Initialize * 를 선택합니다.
+
설정이 완료되면 클러스터의 관리 IP 주소로 리디렉션됩니다.

. 네트워크 * 아래에서 * 프로토콜 구성 * 을 선택합니다.
+
[cols="2"]
|===
| IP(iSCSI 및 NVMe/TCP)를 구성하려면 다음을 수행합니다. | FC 및 NVMe/FC를 구성하려면 다음을 수행합니다. 


 a| 
.. IP * 를 선택한 다음 * IP 인터페이스 구성 * 을 선택합니다.
.. Add a subnet * 을 선택합니다.
.. 서브넷의 이름을 입력한 다음 서브넷 IP 주소를 입력합니다.
.. 서브넷 마스크를 입력하고 선택적으로 게이트웨이를 입력한 다음 * 추가 * 를 선택합니다.
.. 방금 만든 서브넷을 선택한 다음 * 저장 * 을 선택합니다.
.. 저장 * 을 선택합니다.

 a| 
.. FC * 를 선택한 다음 * Configure FC interfaces * 및/또는 * Configure NVMe/FC interfaces * 를 선택합니다.
.. FC 및/또는 NVMe/FC 포트를 선택한 다음 * Save * 를 선택합니다.


|===
. 필요한 경우 를 다운로드하고 link:https://mysupport.netapp.com/site/tools/tool-eula/activeiq-configadvisor["ActiveIQ Config Advisor"]실행하여 구성을 확인합니다.
+
ActiveIQ Config Advisor 는 일반적인 구성 오류를 확인하는 NetApp 시스템용 툴입니다.



.다음 단계
이제 link:set-up-data-access.html["데이터 액세스를 설정합니다"]SAN 클라이언트에서 ASA R2 시스템으로 전환할 준비가 되었습니다.
