---
sidebar: sidebar 
permalink: install-setup/install-setup-requirements.html 
keywords: asa r2, install, setup, requirements, cautions 
summary: ASA R2 스토리지 시스템 및 스토리지 셸프에 필요한 장비 및 인양 주의 사항을 검토합니다. 
---
= ASA R2 스토리지 시스템의 설치 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2 스토리지 시스템 및 스토리지 셸프에 필요한 장비 및 인양 주의 사항을 검토합니다.



== 설치에 필요한 장비

ASA R2 스토리지 시스템을 설치하려면 다음과 같은 장비와 툴이 필요합니다.

* 웹 브라우저에 액세스하여 스토리지 시스템을 구성합니다
* 정전기 방전(ESD) 스트랩
* 플래시
* USB/직렬 연결이 있는 랩톱 또는 콘솔
* NS224 스토리지 쉘프 ID를 설정하기 위한 종이 클립 또는 끝이 뾰족한 볼펜
* Phillips #2 드라이버




== 인양 주의 사항

ASA R2 스토리지 시스템과 NS224 스토리지 쉘프는 무겁습니다. 이러한 품목을 들어 올리거나 이동할 때는 주의를 기울이십시오.



=== 스토리지 시스템 중량

ASA R2 스토리지 시스템을 이동하거나 들어올릴 때 필요한 예방 조치를 취하십시오.

[role="tabbed-block"]
====
.ASA A1K 를 참조하십시오
--
ASA A1K 저장 장치 시스템의 무게는 최대 28.5kg(62.83파운드)입니다. 시스템을 인양하려면 두 사람 또는 유압 리프트를 사용합니다.

image::../media/drw_a1k_weight_caution_ieops-1698.svg[AFF A1K 인양 주의 아이콘]

--
.ASA A70 및 ASA A90
--
ASA A70 스토리지 시스템 또는 ASA A90 스토리지 시스템의 무게는 최대 68.8kg(151.68파운드)입니다. 시스템을 인양하려면 4명 또는 유압 리프트를 사용합니다.

image::../media/drw_a70-90_weight_icon_ieops-1730.svg[AFF A90 를 참조하십시오]

--
====


=== 보관 선반 무게

NS224 보관 선반은 무게가 최대 30.29kg(66.78lbs)입니다. 보관 선반을 들어 올리려면 두 사람이 함께 있거나 유압식 리프트를 사용하십시오. 선반 무게의 균형을 잃지 않도록 모든 구성 요소를 보관 선반(전면 및 후면 모두)에 보관하십시오.

image::../media/drw_ns224_lifting_weight_ieops-1716.svg[NS224 인양 주의]

.관련 정보
* https://library.netapp.com/ecm/ecm_download_file/ECMP12475945["안전 정보 및 규정 고지"^]


.다음 단계
하드웨어 요구 사항을 검토한 후link:prepare-hardware.html["ASA R2 스토리지 시스템 설치를 준비합니다"]
