---
sidebar: sidebar 
permalink: install-setup/set-up-data-access.html 
keywords:  
summary:  
---
= SAN 호스트에서 ASA R2 스토리지 시스템으로의 데이터 액세스가 가능합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 액세스를 설정하려면 ONTAP에서 올바르게 작동하기 위해 SAN 클라이언트의 중요 매개 변수 및 설정이 올바르게 구성되어 있는지 확인해야 합니다. VMware 환경을 위한 스토리지를 제공하는 경우 간단히 ASA R2 스토리지를 관리할 수 있도록 OTV 10.3을 설치해야 합니다.



== SAN 호스트에서 데이터 액세스 설정

SAN 호스트에서 ASA R2 시스템에 대한 데이터 액세스를 설정하는 데 필요한 구성은 호스트 운영 체제 및 프로토콜에 따라 다릅니다. 최상의 성능과 성공적인 페일오버를 위해서는 올바른 구성이 중요합니다.

link:https://docs.netapp.com/us-en/ontap-sanhost/hu_vsphere_8.html["VMware vSphere SCSI 클라이언트"^]link:https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["VMware vSphere NVMe 클라이언트"^]link:https://docs.netapp.com/us-en/ontap-sanhost/overview.html["기타 SAN 클라이언트"^]ASA R2 시스템에 접속하도록 호스트를 적절히 구성하려면 에 대한 ONTAP SAN 호스트 설명서를 참조하십시오.



== VMware 가상 시스템을 마이그레이션합니다

VM 워크로드를 ASA 스토리지 시스템에서 ASA R2 스토리지 시스템으로 마이그레이션해야 하는 경우, NetApp 를 사용하여 link:https://www.vmware.com/products/cloud-infrastructure/vsphere/vmotion["VMware vSphere vMotion을 참조하십시오"^]무중단 실시간 데이터 마이그레이션을 수행하는 것이 좋습니다.



== ASA R2 시스템을 VMware 환경에서 스토리지 공급자로 구성합니다

VMware용 ONTAP 툴을 사용하면 ASA R2 시스템을 VMware 환경에서 스토리지 공급자로 쉽게 설정할 수 있습니다.

VMware vSphere용 ONTAP 툴은 VMware ESXi 호스트에서 가상 머신을 쉽게 관리할 수 있도록 vCSA(vCenter Server Virtual Appliance)와 함께 작동하는 툴 세트입니다.

ASA R2 시스템은 link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/concepts/ontap-tools-overview.html["VMware vSphere 10.3용 ONTAP 툴"^]이상에서 지원됩니다.

다음 작업을 수행하는 방법  및 사용 방법에 대해 link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/deploy/ontap-tools-deployment.html["VMware용 ONTAP 툴을 구축합니다"^]알아봅니다.

* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/add-vcenter.html["vCenter Server 인스턴스를 추가합니다"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/configure-esx-server-multipath-and-timeout-settings.html["ESXi 호스트 설정을 구성합니다"^]
* link:https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere-10/configure/discover-storage-systems-and-hosts.html["ASA R2 스토리지 시스템 및 호스트를 검색합니다"^]


.다음 단계
link:../manage-data/provision-san-storage.html["스토리지 용량 할당"]SAN 호스트에서 스토리지 유닛에 데이터를 읽고 쓸 수 있도록 할 준비가 되었습니다.
