---
sidebar: sidebar 
permalink: secure-data/respond-anti-ransomware-protection-alerts.html 
keywords: asa r2, secure data, data security, anti-ransomware, autonomous ransomware protection, arp, arp/ai, alerts, respond, warnings, security 
summary: 시스템 관리자에서 잠재적인 랜섬웨어 공격에 대한 경고를 보고 조치를 취하세요. 
---
= ASA r2 스토리지 시스템에서 AI 알림을 통해 자율적인 랜섬웨어 보호에 대응
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인공지능(ARP/AI)을 활용한 자율 랜섬웨어 보호 기능이 ASA r2 시스템 스토리지 유닛 하나 이상에서 비정상적인 활동을 감지하면 시스템 관리자 대시보드에 경고가 생성됩니다. 경고를 확인하고 활동을 확인한 후, 필요한 경우 데이터에 대한 잠재적 위협을 차단하기 위한 조치를 취해야 합니다.

ARP/AI 경고 메시지가 표시되면 조치를 취하기 전에 적절한 애플리케이션 무결성 검사기를 사용하여 스토리지 유닛의 데이터 무결성을 확인해야 합니다. 스토리지 유닛의 데이터 무결성을 확인하면 해당 활동이 허용 가능한 수준인지 아니면 잠재적인 랜섬웨어 공격인지 판단하는 데 도움이 됩니다.

[cols="2,2"]
|===
| 비정상적인 활동이 발생하면... | 그러면 이렇게 하세요... 


| 허용 가능 | 해당 활동을 거짓 양성으로 표시합니다. 


| 잠재적인 랜섬웨어 공격 | 해당 활동을 랜섬웨어 공격의 가능성이 있는 활동으로 표시합니다. 


| 불확정 | 즉각적인 조치를 취하지 마십시오. 최대 7일 동안 저장 장치를 모니터링하십시오. 저장 장치가 계속 정상적으로 작동하면 해당 활동을 오탐(false positive)으로 표시하십시오. 저장 장치에서 비정상적인 활동이 계속 나타나면 해당 활동을 잠재적인 랜섬웨어 공격으로 표시하십시오. 
|===
.단계
. System Manager에서 * 대시보드 * 를 선택합니다.
+
ARP가 하나 이상의 저장 장치에서 비정상적인 활동을 감지하면 *경고* 아래에 메시지가 나타납니다.

. 경고 메시지를 선택하세요.
. *이벤트 개요*에서 비정상적인 활동이 있는 저장 장치 수를 나타내는 *경고* 메시지를 선택합니다.
. *비정상적인 활동이 있는 보관 장치*에서 보관 장치를 선택하세요.
. *보안*을 선택하세요.
+
저장 장치에 비정상적인 활동이 있는 경우 *랜섬웨어 방지* 아래에 메시지가 표시됩니다.

. *작업 선택*을 선택하세요.
. *거짓 양성으로 표시*를 선택하거나 *잠재적 랜섬웨어 공격으로 표시*를 선택합니다.

