---
sidebar: sidebar 
permalink: learn-more/hardware-comparison.html 
keywords: compare asa r2, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20, asa c30, hardware comparison, asa r2 
summary: ASA 시스템은 SAN 전용 솔루션에 최적화된 하드웨어 지원을 제공합니다. ASA R2 시스템은 하드웨어 및 소프트웨어를 최적화합니다. 
searchtitle: ASA R2 시스템을 다른 ONTAP 시스템과 비교합니다 
---
= ASA R2 시스템을 다른 ONTAP 시스템과 비교합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 시스템은 모든 플래시 솔루션을 기반으로 SAN 전용 환경을 위한 하드웨어 및 소프트웨어 솔루션을 제공합니다. ASA r2 시스템은 ONTAP 특성, 스토리지 계층 및 지원 프로토콜 구현 측면에서 다른 ONTAP 시스템(ASA, AFF, FAS )과 차별화됩니다.

ASA r2 시스템으로 분류되는 것은 다음과 같습니다.

* ASA A1K 를 참조하십시오
* ASA A90 를 참조하십시오
* ASA A70 를 참조하십시오
* ASA A50
* ASA A30
* ASA A20
* ASA C30




== 성격 차이

ASA R2 시스템에서 ONTAP 소프트웨어가 간소화되어 필수 SAN 기능을 지원하는 동시에 SAN 관련 기능이 아닌 기능의 가시성과 가용성을 제한합니다. 예를 들어, ASA R2 시스템에서 실행되는 System Manager에는 NAS 클라이언트의 홈 디렉토리를 생성하는 옵션이 표시되지 않습니다. 이 간소화된 ONTAP 버전은 _ ASA R2 Personality _ 로 식별됩니다. ASA 시스템에서 실행되는 ONTAP는 _ ASA ONTAP Personality _ 로 식별됩니다. AFF 및 FAS ONTAP 시스템에서 실행되는 ONTAP는 _ Unified ONTAP Personality _ 로 식별됩니다. ONTAP 퍼스낼리티의 차이는 ONTAP 명령 참조(man 페이지), REST API 사양 및 해당되는 경우 EMS 메시지에서 참조된다.

ONTAP 스토리지의 특성은 System Manager 또는 ONTAP CLI에서 확인할 수 있습니다.

* System Manager 메뉴에서 * 클러스터 > 개요 * 를 선택합니다.
* CLI에서 다음을 입력하세요. `system node show -personality -is-disaggregated`


ASA r2 시스템의 경우 _개성_은 _ASA r2_이고 _is-disaggregated_의 상태는 _true_입니다.

ONTAP 스토리지 시스템의 특성은 변경할 수 없습니다.



== 저장 계층 차이점

ASA r2 시스템은 FAS, AFF, ASA 시스템에서 사용하는 저장 계층과 다른 단순화된 저장 계층을 사용합니다.

.FAS, AFF 및 ASA 시스템
FAS, AFF 및 ASA 시스템의 스토리지 계층은 집계를 스토리지의 기본 단위로 사용합니다. 집계는 스토리지 시스템에서 사용 가능한 특정 디스크 집합을 소유합니다. 집계는 자신이 소유한 디스크의 공간을 LUN 및 네임스페이스 볼륨에 할당합니다. 이러한 시스템을 통해 ONTAP 사용자는 집계, 볼륨, LUN 및 네임스페이스를 생성하고 수정할 수 있습니다.

.ASA r2 시스템
ASA r2 시스템의 스토리지 계층은 집계 대신 스토리지 가용성 영역(SAZ)을 사용합니다. 스토리지 가용성 영역은 단일 HA 쌍의 두 노드 모두에서 사용할 수 있는 공통 스토리지 풀입니다. HA 쌍의 두 노드는 공유 스토리지 가용성 영역의 모든 사용 가능한 디스크에 액세스할 수 있습니다. 예를 들어, 2노드 ASA r2 System ONTAP 클러스터에는 클러스터의 두 노드 모두 액세스할 수 있는 스토리지 가용성 영역이 하나 있습니다. 4노드 ASA r2 System ONTAP 클러스터에는 두 개의 스토리지 가용성 영역이 있습니다. 클러스터의 각 HA 쌍은 스토리지 가용성 영역 중 하나에 액세스할 수 있습니다.

스토리지 유닛(LUN 또는 NVMe 네임스페이스 기반)이 생성되면 ONTAP 해당 스토리지 가용 영역에 볼륨을 자동으로 생성하여 스토리지 유닛을 저장합니다. 새로 생성된 볼륨은 최적의 성능과 균형 잡힌 용량 활용을 위해 스토리지 가용 영역 내에 자동으로 배치됩니다. 스토리지 가용 영역 내에서 용량 활용률은 사용자의 ONTAP 버전에 따라 균형을 이룹니다. link:administer/space-balancing.html["ASA r2 클러스터에서 용량 균형 조정에 대해 알아보세요."^].



== ASA r2 시스템 차이점 요약

ASA r2 시스템은 다음과 같은 면에서 FAS, AFF, ASA 시스템과 다릅니다.

[cols="1h,2,2,2,2"]
|===
|  | ASA r2 를 참조하십시오 | ASA | AFF | FAS 


 a| 
* ONTAP 성격 *
| ASA r2 를 참조하십시오 | ASA | 통합 | 통합 


 a| 
* SAN 프로토콜 지원 *
| 예 | 예 | 예 | 예 


 a| 
* NAS 프로토콜 지원 *
| 아니요 | 아니요 | 예 | 예 


 a| 
* 스토리지 계층 지원 *
| 스토리지 가용 영역 | 애그리게이트 | 애그리게이트 | 애그리게이트 
|===
이러한 자동화되고 간소화된 스토리지 관리 방식으로 인해 ASA r2 시스템에서는 특정 System Manager 옵션, ONTAP 명령 및 REST API 엔드포인트를 사용할 수 없거나 사용이 제한됩니다. 예를 들어, ASA r2 시스템에서는 볼륨 생성 및 관리가 자동화되어 있기 때문에 System Manager에 *볼륨* 메뉴가 나타나지 않고  `volume create` 명령이 지원되지 않습니다. link:cli-support.html["지원되지 않는 ASA r2 명령에 대해 자세히 알아보세요"] .

ONTAP CLI(Command Line Interface) 및 REST API와 관련된 ASA R2 시스템과 FAS, AFF 및 ASA 시스템의 주요 차이점은 아래에 설명되어 있습니다.

.프로토콜 서비스를 사용한 기본 스토리지 VM 생성
새로운 클러스터에는 SAN 프로토콜이 활성화된 기본 데이터 저장 가상 머신(VM)이 자동으로 포함됩니다.  IP 데이터 LIF는 iSCSI 및 NVMe/TCP 프로토콜을 지원하며 다음을 사용합니다. `default-data-blocks` 기본적으로 서비스 정책이 적용됩니다.

.자동 볼륨 생성
스토리지 유닛(LUN 또는 네임스페이스)을 생성하면 스토리지 가용 영역에서 볼륨이 자동으로 생성됩니다. 결과적으로 공통 네임스페이스가 단순화됩니다. 스토리지 유닛을 삭제하면 연결된 볼륨이 자동으로 삭제됩니다.

.씬 및 일반 프로비저닝으로 변경
스토리지 유닛은 항상 ASA R2 스토리지 시스템에서 씬 프로비저닝됩니다. 일반 프로비저닝은 지원되지 않습니다.

.데이터 압축의 변경 사항
온도에 민감한 스토리지 효율성이 ASA R2 시스템에는 적용되지 않습니다. ASA R2 시스템에서 압축은 _hot_(자주 액세스하는) 데이터 또는 _cold_(자주 액세스하지 않는) 데이터를 기반으로 하지 않습니다. 데이터의 콜드 데이터가 될 때까지 기다리지 않고 압축을 시작합니다.

.를 참조하십시오
* 에 대해 자세히 link:https://docs.netapp.com/us-en/ontap-systems-family/intro-family.html["ONTAP 하드웨어 시스템"^]알아보십시오.
* 에서 ASA 및 ASA R2 시스템에 대한 전체 구성 지원 및 제한 사항을 link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]참조하십시오.
* 에 대해 자세히 link:https://www.netapp.com/pdf.html?item=/media/85736-ds-4254-asa.pdf["NetApp ASA"^]알아보십시오.

