---
sidebar: sidebar 
permalink: learn-more/rest-api-support.html 
keywords: asa, asa r2, rest, rest api, asa r2 rest api, asa a1k, asa a90, asa a70, asa a50, asa a30, asa a20 
summary: ASA R2 REST API는 통합된 ONTAP 퍼스낼리티와 함께 제공되는 REST API를 기반으로 하며, ASA R2 퍼스낼리티의 고유한 특성과 기능에 맞게 많은 변경이 적용되었습니다. 
---
= ASA R2에 대한 REST API 지원
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ASA R2 REST API는 통합된 ONTAP 퍼스낼리티와 함께 제공되는 REST API를 기반으로 하며, ASA R2 퍼스낼리티의 고유한 특성과 기능에 맞게 많은 변경이 적용되었습니다.



== API 변경 유형

ASA R2 시스템 REST API와 FAS, AFF 및 ASA 시스템에서 사용할 수 있는 유니파이드 ONTAP REST API 간에는 여러 가지 차이점이 있습니다. 변경 유형을 이해하면 온라인 API 참조 문서를 보다 잘 활용할 수 있습니다.

.새로운 ASA R2 엔드포인트는 유니파이드 ONTAP에서 지원되지 않습니다
유니파이드 ONTAP에서는 사용할 수 없는 ASA R2 REST API에 여러 엔드포인트가 추가되었습니다.

예를 들어, 새로운 블록 볼륨 엔드포인트가 ASA R2 시스템용 REST API에 추가되었습니다. 블록 볼륨 엔드포인트는 LUN 및 NVMe 네임스페이스 개체에 대한 액세스를 제공하여 리소스를 종합적으로 볼 수 있도록 지원합니다. REST API를 통해서만 사용할 수 있습니다.

또 다른 예로, * storage-units * 엔드포인트는 LUN 및 NVMe 네임스페이스를 집계한 보기로 제공합니다. 여러 개의 끝점이 있으며 모두 기반으로 하거나 에서 파생됩니다. `/api/storage/storage-units`  `/api/storage/luns`및 도 검토해야 `/api/storage/namespaces` 합니다.

.일부 끝점에 사용되는 HTTP 메서드에 대한 제한 사항
ASA R2에서 사용할 수 있는 여러 끝점에는 Unified ONTAP와 비교하여 사용할 수 있는 HTTP 메서드가 제한되어 있습니다. 예를 들어, `/api/protocols/nvme/services` ASA R2 시스템에서 엔드포인트를 사용할 때는 POST 및 DELETE가 허용되지 않습니다.

.끝점 및 HTTP 메서드에 대한 속성 변경
일부 ASA R2 시스템 끝점 및 메서드 조합은 통합 ONTAP 속성에서 사용할 수 있는 정의된 모든 속성을 지원하지 않습니다. 예를 들어, 끝점에서 패치를 사용하는 경우 `/api/storage/volumes/{uuid}` ASA R2에서는 다음을 비롯한 몇 가지 속성이 지원되지 않습니다.

* `autosize.maximum`
* `autosize.minimum`
* `autosize.mode`


.내부 처리의 변경
ASA R2가 특정 REST API 요청을 처리하는 방법은 몇 가지 변경되었습니다. 예를 들어, 끝점이 있는 삭제 요청은 `/api/storage/luns/{uuid}` 비동기적으로 처리됩니다.



== OAuth 2.0으로 보안 강화

OAuth 2.0은 업계 표준 인증 프레임워크입니다. 서명된 액세스 토큰을 기반으로 보호된 리소스에 대한 액세스를 제한하고 제어하는 데 사용됩니다. System Manager를 사용하여 OAuth 2.0을 구성하여 ASA R2 시스템 리소스를 보호할 수 있습니다.

System Manager로 OAuth 2.0을 설정한 후 REST API 클라이언트의 액세스를 제어할 수 있습니다. 먼저 인증 서버에서 액세스 토큰을 얻어야 합니다. 그런 다음 REST 클라이언트는 HTTP 승인 요청 헤더를 사용하여 토큰을 ASA R2 클러스터에 베어러 토큰으로 전달합니다. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap/authentication/overview-oauth2.html["OAuth 2.0을 사용한 인증 및 권한 부여"^] 참조하십시오.



== Swagger UI를 통해 ASA R2 API 참조 문서에 액세스합니다

ASA R2 시스템에서 Swagger UI를 통해 REST API 참조 문서에 액세스할 수 있습니다.

.이 작업에 대해
REST API에 대한 자세한 내용은 ASA R2 참조 문서 페이지에 액세스해야 합니다. 이 과정에서 문자열 * 플랫폼 사양 * 을 검색하여 API 호출 및 속성에 대한 ASA R2 시스템 지원에 대한 세부 정보를 찾을 수 있습니다.

.시작하기 전에
다음 항목이 있어야 합니다.

* ASA R2 시스템의 클러스터 관리 LIF의 IP 주소 또는 호스트 이름입니다
* REST API 액세스 권한이 있는 계정의 사용자 이름 및 암호


.단계
. 브라우저에 URL을 입력하고 * Enter *:+를 누릅니다
`https://<ip_address>/docs/api`
. 관리자 계정을 사용하여 로그인합니다.
+
ASA R2 API 설명서 페이지는 주요 리소스 범주로 구성된 API 호출과 함께 표시됩니다.

. ASA R2 시스템에만 해당되는 API 호출 예를 보려면 * SAN * 범주로 스크롤한 다음 * Get/storage/storage-units * 를 클릭합니다.

