---
sidebar: sidebar 
permalink: learn-more/software-support-limitations.html 
keywords: asa r2, asa a1k, asa a90, asa a70, asa, a50, asa a30, asa a20, asa c30, unsupported features 
summary: ASA R2 시스템은 SAN 솔루션에 대해 광범위한 지원을 제공하지만 특정 ONTAP 소프트웨어 기능은 지원되지 않습니다. 
---
= ASA R2 스토리지 시스템에 대한 ONTAP 소프트웨어 지원 및 제한 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2 시스템은 SAN 솔루션에 대해 광범위한 지원을 제공하지만 특정 ONTAP 소프트웨어 기능은 지원되지 않습니다.

.ASA R2 시스템은 다음을 지원하지 않습니다.
* FabricPool
* LUN 일반 프로비저닝
* MetroCluster
* NetApp Aggregate Encryption(NAE)
* 오브젝트 프로토콜
* ONTAP S3 SnapMirror 및 S3 API
* SnapLock
+
SnapLock Compliance 및 Enterprise 모드는 SAN 환경의 기본 클러스터에서 지원되지 않습니다. SnapLock for SnapVault는 보조 클러스터에서 지원됩니다.

* SnapMirror 복제는 다음과 같은 제한 사항이 있는 ASA r2 시스템에서 지원됩니다.
+
** SnapMirror 동기 복제는 지원되지 않습니다.
** SnapMirror 비동기 복제는 두 개의 ASA r2 시스템 간에만 지원됩니다. SnapMirror 비동기 복제는 ASA r2 시스템과 ASA, AFF 또는 FAS 시스템 또는 클라우드 사이에서는 지원되지 않습니다.
+
자세히 알아보세요link:../data-protection/pre-defined-protection-policies.html["ASA r2 시스템에서 지원되는 SnapMirror 복제 정책"] .

** SnapMirror Active Sync는 두 개의 ASA r2 시스템 간에만 지원됩니다.
+
자세히 알아보세요link:../data-protection/snapmirror-active-sync.html["ASA r2 시스템의 SnapMirror Active Sync"] .





.ASA R2 시스템은 다음을 지원합니다.
* 이중 계층 암호화
+
ASA r2 시스템은 자체 암호화 드라이브(SED)를 사용한 하드웨어 암호화와 NetApp 볼륨 암호화(NVE) 기술을 사용한 소프트웨어 암호화를 지원합니다. link:../secure-data/encrypt-data-at-rest.html["이중 레이어 암호화를 적용하는 방법에 대해 알아봅니다"] ASA r2 시스템의 데이터를 보호합니다.



.를 참조하십시오
* link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^]ASA R2 하드웨어 지원 및 제한 사항에 대한 자세한 내용은 를 참조하십시오.

