---
sidebar: sidebar 
permalink: monitor/monitor-storage.html 
keywords: monitor, storage, cluster, utilization, usage 
summary: 스토리지 활용률을 모니터링하여 현재 및 미래의 워크로드를 처리하는 데 필요한 스토리지 용량이 있는지 확인하십시오. 
searchtitle: ONTAP System Manager | ASA R2를 사용하여 공간 활용률을 모니터링합니다 
---
= ASA R2 스토리지 시스템에서 클러스터 및 스토리지 유닛 활용도를 모니터링합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP System Manager를 사용하여 스토리지 활용률을 모니터링하여 현재 및 미래의 워크로드를 처리하는 데 필요한 스토리지 용량을 확보하십시오.



== 클러스터 활용률을 모니터링합니다

클러스터에서 사용하는 스토리지 양을 정기적으로 모니터링하여 필요한 경우 공간이 부족해지기 전에 클러스터 용량을 확장할 준비가 되었는지 확인합니다.

.단계
. System Manager에서 * 대시보드 * 를 선택합니다.
. Capacity * 에서 클러스터에서 사용된 물리적 공간의 양과 사용 가능한 공간의 양을 확인합니다.
+
데이터 축소율은 스토리지 효율성을 통해 절약된 공간의 양을 나타냅니다.



.다음 단계
클러스터에 공간이 부족하거나 향후 요구 사항을 충족할 수 있는 용량이 없는 경우 link:../administer/increase-storage-capacity.html["새 드라이브를 추가합니다"]ASA R2 시스템을 구축하여 스토리지 용량을 늘려야 합니다.



== 스토리지 가용 영역 활용률 모니터링

ASA R2 시스템의 각 HA 쌍은 _ 스토리지 가용성 영역 _ 이라는 공통 스토리지 풀을 사용합니다. 스토리지 가용 영역은 스토리지 시스템의 모든 가용 디스크에 액세스할 수 있으며 HA 쌍의 두 노드에 표시됩니다.

클러스터에 4개 이상의 노드가 있는 경우 각 HA 쌍의 스토리지 가용성 영역에서 사용하는 공간의 양을 볼 수 있습니다. 2노드 클러스터에는 이 메트릭을 사용할 수 없습니다.

.단계
. System Manager에서 * Cluster * 를 선택한 다음 * Overview * 를 선택합니다.
+
스토리지 가용 영역 활용률에 대한 요약이 클러스터의 각 HA 쌍에 대해 표시됩니다.

. 보다 자세한 메트릭을 원하는 경우 특정 스토리지 가용성을 선택합니다.
+
개요 * 아래에 스토리지 가용 영역의 용량, 사용된 공간 및 데이터 축소율이 표시됩니다.

+
Storage units * 아래에 스토리지 가용 영역의 모든 스토리지 유닛 목록이 표시됩니다.



.다음 단계
스토리지 가용 영역에서 공간이 부족하면 다른 스토리지 가용 영역을 계획하여 클러스터 전체에서 스토리지 사용률의 균형을 조정해야 link:../manage-data/move-storage-units.html["저장 장치를 이동합니다"]합니다.



== 스토리지 유닛 사용률을 모니터링합니다

스토리지 유닛에서 사용하는 스토리지 양을 모니터링하여 비즈니스 요구 사항에 따라 스토리지 유닛의 크기를 사전에 늘릴 수 있습니다.

.단계
. System Manager에서 * Storage * 를 선택합니다.
. 모니터링할 스토리지 유닛을 선택한 다음 * Overview * 를 선택합니다.
. 스토리지 * 에서 다음을 확인합니다.
+
** 저장 장치의 크기입니다
** 사용된 공간의 양입니다
** 데이터 축소율
+
데이터 축소율은 스토리지 효율성을 통해 절약된 공간의 양을 나타냅니다

** 스냅샷이 사용되었습니다
+
사용된 스냅샷은 스냅샷에 사용되는 스토리지의 양을 나타냅니다.





.다음 단계
저장 장치 용량이 거의 다 되면 link:../manage-data/modify-storage-units.html["스토리지 유닛을 수정합니다"]크기를 늘려야 합니다.
