---
sidebar: sidebar 
permalink: administer/increase-storage-capacity.html 
keywords: increase, capacity, node, shelf, drive, expand, storage, asa r2, asa r2, asa a1k, asa 70, asa 90 
summary: 노드 또는 쉘프에 드라이브를 추가하여 ASA R2 스토리지 유닛의 용량을 늘립니다. 
---
= ASA R2 스토리지 시스템에서 스토리지 용량을 늘립니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
노드나 쉘프에 드라이브를 추가하여 ASA R2 시스템의 스토리지 용량을 늘립니다.



== NetApp Hardware Universe를 사용하여 새 드라이브 설치를 준비합니다

새 드라이브를 노드 또는 쉘프에 설치하기 전에 NetApp Hardware Universe를 사용하여 추가하려는 드라이브가 ASA R2 플랫폼에서 지원되는지 확인하고 새 드라이브에 대한 올바른 슬롯을 식별하십시오. 드라이브를 추가할 수 있는 올바른 슬롯은 플랫폼 모델과 ONTAP 버전에 따라 다릅니다. 경우에 따라 특정 슬롯에 순차적으로 드라이브를 추가해야 할 수도 있습니다.

.단계
. 로 이동합니다link:https://hwu.netapp.com/["NetApp Hardware Universe를 참조하십시오"^].
. 제품 * 에서 하드웨어 구성을 선택합니다.
. ASA R2 플랫폼을 선택합니다.
. ONTAP 버전을 선택한 다음 * 결과 표시 * 를 선택합니다.
. 그래픽 아래에서 * 대체 보기를 보려면 여기를 클릭하십시오 * 를 선택한 다음 구성과 일치하는 보기를 선택하십시오.
. 구성 보기를 사용하여 새 드라이브가 지원되는지, 올바른 설치 슬롯이 지원되는지 확인합니다.


.결과
새 드라이브가 지원되는지 확인했으며 설치에 적합한 슬롯을 알고 있습니다.



== ASA R2에 새 드라이브를 설치합니다

단일 절차에서 추가해야 하는 최소 드라이브 수는 6개입니다. 단일 드라이브를 추가하면 성능이 저하될 수 있습니다.

.이 작업에 대해
각 드라이브에 대해 이 절차의 단계를 반복해야 합니다.

.단계
. 적절하게 접지합니다.
. 플랫폼 전면에서 베젤을 조심스럽게 분리합니다.
. 새 드라이브를 올바른 슬롯에 삽입합니다.
+
.. 캠 핸들이 열린 위치에 있는 상태에서 두 손을 사용하여 새 드라이브를 삽입합니다.
.. 드라이브가 멈출 때까지 누릅니다.
.. 드라이브가 중간 평면에 완전히 장착되고 핸들이 제자리에 고정되도록 캠 핸들을 닫습니다.
+
캠 핸들이 드라이브 면과 올바르게 정렬되도록 캠 핸들을 천천히 닫아야 합니다.



. 드라이브의 작동 LED(녹색)가 켜져 있는지 확인합니다.
+
** LED가 켜져 있으면 드라이브에 전원이 들어옵니다.
** LED가 깜박이면 드라이브에 전원이 들어오고 I/O가 진행 중인 것입니다. 드라이브 펌웨어를 업데이트하는 경우에도 LED가 깜박입니다.
+
현재 펌웨어 버전이 없는 새 드라이브에서 드라이브 펌웨어가 중단 없이 자동으로 업데이트됩니다.



. 노드가 드라이브 자동 할당으로 구성되어 있는 경우 ONTAP가 새 드라이브를 노드에 자동으로 할당할 때까지 기다릴 수 있습니다. 노드가 드라이브 자동 할당으로 구성되지 않았거나 원하는 경우 드라이브를 수동으로 할당할 수 있습니다.
+
새 드라이브는 노드에 할당될 때까지 인식되지 않습니다.



.다음 단계
새 드라이브가 인식되면 드라이브가 추가되었고 소유권이 올바르게 지정되었는지 확인합니다.
