---
sidebar: sidebar 
permalink: administer/rebalance-workloads.html 
keywords: rebalance workload, workload rebalancing, node balancing, asa r2 
summary: ONTAP 9.17.1부터 ONTAP 최적의 성능을 위해 ASA r2 시스템 HA 쌍의 노드 간 작업 부하를 자동으로 재조정합니다. 
---
= ASA r2 스토리지 시스템의 노드 간 워크로드 재조정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 9.17.1부터 ONTAP 최적의 성능을 위해 ASA r2 시스템 HA 쌍의 노드 간 워크로드를 자동으로 재분배합니다. 예를 들어, 한 노드의 사용률이 70%로 증가하는 반면 HA 파트너의 사용률은 30%에 불과한 경우, ONTAP 각 노드의 사용률이 더 일치하도록 워크로드를 자동으로 이동합니다. HA 쌍의 노드는 동일한 스토리지 가용 영역을 공유하므로 워크로드 재분배는 성능에 영향을 미치지 않는 복사 없는 작업입니다.



== 자동 워크로드 재조정을 위한 기본 평가 기간 수정

ONTAP 9.17.1로 업그레이드하거나 새 ONTAP 9.17.1 ASA r2 클러스터를 초기화한 후 14일이 지나면 기본적으로 자동 워크로드 리밸런싱이 활성화됩니다. ONTAP 명령줄 인터페이스(CLI)를 사용하여 운영 요구 사항에 맞게 기본 평가 기간을 늘리거나 줄일 수 있습니다.


NOTE: 자동 워크로드 리밸런싱이 활성화된 후에는 ASA r2 시스템에서 ONTAP 9.17.1에서 되돌릴 수 없습니다.

.단계
. 평가 기간이 남은 일수를 확인하세요.
+
[source, cli]
----
placement rebalance config show -fields evaluation-window
----
. 재조정 평가 기간 변경:
+
[source, cli]
----
placement rebalance config modify -evaluation-window <number_of_evaluation_days>
----
+
다음 예에서는 남은 평가 기간을 10일로 설정합니다.

+
[listing]
----
placement rebalance config modify -evaluation-window 10
----




== 자동 작업 부하 재조정 설정 수정

자동 워크로드 리밸런싱은 ONTAP 9.17.1로 업그레이드하거나 새 ONTAP 9.17.1 ASA r2 클러스터를 초기화한 후 14일 후에 기본적으로 활성화됩니다. 기본 설정을 변경하여 자동 워크로드 리밸런싱을 비활성화하거나, 불균형 워크로드를 자동으로 이동하지 않고 플래그를 지정하도록 권고 상태로 설정할 수 있습니다.

.단계
. 현재 노드에 설정된 재조정 모드를 확인하세요.
+
[source, cli]
----
placement rebalance config show -fields mode
----
. 자동 작업 부하 재분배 설정을 수정합니다.
+
[source, cli]
----
placement rebalance config modify -mode <disabled|advisory|automated>
----
. 재조정 모드가 수정되었는지 확인하세요.
+
[source, cli]
----
placement rebalance config show -fields mode
----




== 수동으로 작업 부하 재조정을 트리거합니다.

자동 워크로드 리밸런싱을 비활성화한 경우에도 워크로드 리밸런싱을 수동으로 트리거할 수 있습니다. 이는 일정 기간의 수동 조정 후 워크로드를 리밸런싱하거나 리밸런싱 모드를 *권고*로 설정하고 워크로드 플래그에 따라 조치를 취하려는 경우에 유용합니다.

.단계
. 현재 노드에 설정된 재조정 모드를 확인하세요.
+
[source, cli]
----
placement rebalance config show -fields mode
----
. 재조정 모드가 *권고*로 설정되어 있지 않으면 *권고*로 설정합니다.
+
[source, cli]
----
placement rebalance config modify -mode advisory
----
. 수동으로 워크로드 재조정을 트리거합니다.
+
[source, cli]
----
balanced-placement rebalance execute
----
. 재조정 작업의 상태를 확인하세요.
+
[source, cli]
----
placement rebalance config show-evaluation
----


.다음 단계
재조정 모드를 *자동* 또는 *비활성화*로 설정하려면 다음을 사용할 수 있습니다.  `placement rebalance config modify` 명령.
