---
sidebar: sidebar 
permalink: administer/revert-ontap.html 
keywords: update, revert, ontap, asa r2 
summary: ONTAP는 ASA R2 시스템에서 펌웨어를 자동으로 업데이트합니다. System Manager를 사용하여 자동 업데이트를 사용하지 않도록 설정하고 업데이트를 설치하기 전에 볼 수 있습니다. 
---
= ASA r2 스토리지 시스템에서 ONTAP 되돌리기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 시스템에 대한 ONTAP 소프트웨어 복구는 다른 ONTAP 시스템에 대한 복구와 동일한 프로세스를 따릅니다.

ONTAP 클러스터를 되돌리는 작업은 시스템 중단을 초래할 수 있습니다. 되돌리는 동안 클러스터를 오프라인 상태로 유지해야 합니다. 기술 지원팀의 도움 없이 운영 클러스터를 되돌려서는 안 됩니다. 새 클러스터나 테스트 클러스터는 도움 없이 되돌릴 수 있습니다. 새 시스템이나 테스트 클러스터의 되돌리기가 실패하거나 성공적으로 완료되었지만 운영 환경의 클러스터 성능에 만족하지 못하는 경우 기술 지원팀에 문의하여 도움을 요청하십시오.

link:https://docs.netapp.com/us-en/ontap/revert/task_reverting_an_ontap_cluster.html["ONTAP 클러스터 되돌리기"] .



== ASA r2 시스템에 대한 요구 사항 되돌리기

특정 ASA r2 클러스터 구성에서는 ONTAP 소프트웨어 되돌리기를 시작하기 전에 특정 작업을 수행해야 합니다.



=== ONTAP 9.17.1에서 복귀

ASA r2 시스템에서 ONTAP 9.17.1에서 되돌리는 경우, 되돌리기를 시작하기 전에 다음 작업을 수행해야 합니다.


NOTE: link:../administer/rebalance-workloads.html["자동 워크로드 재조정"]ONTAP 9.17.1로 업그레이드하거나 새로운 ONTAP 9.17.1 ASA r2 클러스터를 초기화한 후 14일이 지나면 기본적으로 활성화됩니다. 자동 워크로드 리밸런싱이 활성화된 후에는 ASA r2 시스템에서 ONTAP 9.17.1에서 되돌릴 수 없습니다.

[cols="2"]
|===
| 만약 당신이 가지고 있다면... | 되돌리기 전에 다음을 수행해야 합니다. 


| SnapMirror 활성 동기화 관계의 계층적 일관성 그룹 | SnapMirror 활성 동기화 관계 제거 


| 활성 수입 관계 | 활성 가져오기 관계 삭제 


| 랜섬웨어 방지 보호 기능 활성화 | 랜섬웨어 방지 보호 비활성화 
|===