---
sidebar: sidebar 
permalink: administer/space-balancing.html 
keywords: capacity, space, rebalancing, balanced, placement, balance, asa r2 
summary: 조직의 명명 규칙에 맞게 또는 기타 관리 상의 이유로 노드 이름을 변경해야 할 수도 있습니다. 
---
= ASA r2 클러스터에서 ONTAP 용량 분산에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA r2 시스템의 경우 ONTAP _균형 배치_를 사용하여 새로 생성된 스토리지 장치를 최적의 성능과 균형 잡힌 스토리지 활용을 위해 가장 적합한 스토리지 가용 영역에 자동으로 배치합니다.  ONTAP 9.17.1 이상 버전을 실행 중인 경우 기존 스토리지 장치에서 사용되는 공간은 동적 공간 균형 조정을 사용하여 균형이 맞춰집니다.  ONTAP 9.16.1을 실행 중인 경우 기존 스토리지 장치에서 사용되는 공간은 복사 기반 워크로드 재균형 조정을 사용하여 균형이 맞춰집니다.

[cols="2"]
|===
| 피처 | ...에서 지원됨 


| 균형 잡힌 배치 | ONTAP 9.16.1 이상 


| 동적 공간 균형 조정 | ONTAP 9.17.1 이상 


| 복사 기반 워크로드 재분배 | ONTAP 9.16.1 버전에서만 사용 가능 
|===
.균형 잡힌 배치
균형 배치 기능을 사용하면 새로 생성된 스토리지 장치가 최적의 성능과 균형 잡힌 스토리지 활용을 위해 최적의 스토리지 가용 영역에 자동으로 배치됩니다.  균형 배치 기능은 ONTAP 9.16.1 이상 버전에서 기본적으로 활성화되어 있습니다.

.동적 공간 균형 조정
ONTAP 동적 공간 균형 조정 기능을 통해 클러스터의 여유 공간을 능동적으로 모니터링하고 스토리지 가용 영역 내에서 스토리지 장치를 자동으로 이동하여 균형 잡힌 공간 활용을 유지합니다.  클러스터 전체 용량 활용률이 80%에 도달하면 EMS 경고가 자동으로 발생하고, 90%에 도달하면 EMS 알림이 자동으로 발생합니다.

ONTAP 9.17.1 이상 버전으로 업그레이드 또는 설치한 후 14일이 지나면 동적 공간 균형 조정이 기본적으로 활성화됩니다.  기본 14일 활성화 기간을 수정해야 하는 경우 NetApp 지원팀에 문의하십시오.  동적 공간 균형 조정이 활성화된 후에는 ONTAP 9.17.1에서 이전 버전으로 되돌릴 수 없습니다.

동적 공간 균형 조정은 클러스터 내 모든 노드의 사용 가능한 공간 평균(전역 평균)을 기준으로 _일반 모드_ 또는 _저용량 공간 모드_로 작동합니다.

* *일반 모드*
+
일반 모드에서 ONTAP 3분마다 동적 공간 균형 조정이 필요한지 여부를 확인합니다.  동적 공간 균형 조정은 다음 조건이 충족될 때 일반 모드로 작동합니다.

+
** 전 세계 평균 여유 공간 비율은 10% 이상입니다.
** 클러스터의 노드 중 적어도 하나는 전체 평균보다 더 많은 여유 공간을 가지고 있습니다.
** 클러스터 내 하나 이상의 노드가 전체 평균보다 여유 공간이 20% 적습니다.


* *저용량 모드*
+
저장 공간이 부족한 모드에서 ONTAP 매분마다 동적 공간 균형 조정이 필요한지 여부를 확인합니다.  동적 공간 균형 조정은 다음 조건이 충족될 때 저용량 모드로 작동합니다.

+
** 전 세계 평균 여유 공간은 10% 미만입니다.
** 클러스터의 노드 중 적어도 하나는 전체 평균보다 더 많은 여유 공간을 가지고 있습니다.
** 클러스터 내 하나 이상의 노드에 전체 평균보다 여유 공간이 적습니다.




.복사 기반 워크로드 재분배
_복사 기반 워크로드 재균형_을 사용하면 스토리지 가용 영역 내에서 스토리지 사용률 불균형이 발생할 경우 ONTAP 불균형을 유발하는 스토리지 장치를 여유 공간이 더 많은 스토리지 가용 영역으로 자동으로 복사합니다.  대상 스토리지 가용 영역에 여유 공간이 충분하지 않으면 ONTAP 로드 밸런싱 작업을 수행하지 않습니다.  복사 기반 워크로드 재균형 조정은 ONTAP 9.16.1을 실행하는 ASA r2 시스템에만 적용되며, 해당 시스템에서는 기본적으로 활성화되어 있습니다.  ONTAP 9.17.1 이상 버전에서는 동적 공간 균형 조정으로 대체되었습니다.

복사 기반 워크로드 재조정의 기본 설정을 수정해야 하는 경우 NetApp 지원팀에 문의하십시오.
