---
sidebar: sidebar 
permalink: administer/upgrade-ontap.html 
keywords: update, firmware, system files, automatic updates, automated updates, asa r2, disable, 
summary: ASA r2 시스템용 ONTAP 소프트웨어 업그레이드는 다른 ONTAP 시스템용 업그레이드와 동일한 프로세스를 따릅니다.  ASA r2 시스템에서 ONTAP 소프트웨어를 업그레이드하면 새롭고 향상된 ONTAP 기능을 활용할 수 있습니다. 
---
= ASA R2 스토리지 시스템에서 ONTAP를 업그레이드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ASA R2 시스템에서 ONTAP 소프트웨어를 업그레이드할 때 새롭고 향상된 ONTAP 기능을 활용하여 비용을 절감하고, 중요한 워크로드를 가속화하고, 보안을 강화하고, 조직에서 사용할 수 있는 데이터 보호 범위를 확장할 수 있습니다.

ASA r2 시스템용 ONTAP 소프트웨어 업그레이드는 다른 ONTAP 시스템의 업그레이드와 동일한 프로세스를 따릅니다. link:https://docs.netapp.com/us-en/ontap/upgrade/create-upgrade-plan.html["Active IQ Digital Advisor 또는 Upgrade Health Checker에서 Upgrade Advisor를 사용하여 업그레이드 준비"^]을(를) 시작하는 것이 좋습니다.

업그레이드 준비를 마친 후에는 link:https://docs.netapp.com/us-en/ontap/upgrade/task_upgrade_andu_sm.html["System Manager에서 자동 무중단 업그레이드(ANDU"^]를 사용하여 업그레이드를 수행하는 것이 좋습니다. ANDU는 ONTAP의 고가용성(HA) 페일오버 기술을 활용하여 업그레이드 중에도 클러스터가 중단 없이 데이터를 계속 제공하도록 보장합니다.

link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ONTAP 소프트웨어 업그레이드"^]에 대해 자세히 알아보십시오.



== 계획된 업그레이드 전에 자동화된 사전 업그레이드 검사를 실행합니다

ONTAP 소프트웨어를 업그레이드하는 과정에 있지 않아도 ONTAP 자동 업그레이드 사전 점검을 실행할 수 있습니다. ONTAP 자동 업그레이드 프로세스와 별도로 업그레이드 전 점검을 실행하면 클러스터에 대해 수행되는 점검 항목을 확인할 수 있으며 실제 업그레이드를 시작하기 전에 수정해야 할 오류 또는 경고 목록을 제공받을 수 있습니다.

ONTAP 9.19.1부터 오류와 경고가 별도로 표시되어 업그레이드 전에 해결해야 할 문제를 쉽게 식별할 수 있습니다.

link:https://docs.netapp.com/us-en/ontap/upgrade/automated-pre-checks.html["ONTAP 자동 사전 업그레이드 검사 실행"^] 방법을 알아보십시오.
