---
sidebar: sidebar 
permalink: videos/video_transcript_provision_san_storage.html 
keywords: frontmatter, front matter 
summary: ONTAP System Manager를 사용하여 ASA R2 스토리지 시스템에서 일반적인 작업을 빠르고 쉽게 수행하는 방법을 보여주는 짧은 비디오를 보십시오. 
---
= ASA R2 시스템에 SAN 스토리지를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
동영상에 대해 다음 `Provision SAN storage on your ASA r2 storage system` 내용이 제공됩니다.

link:videos-common-tasks.html#video_transcript_return_provision_san_storage["페이지로 돌아갑니다"]

ONTAP System Manager를 사용하면 ASA R2 스토리지 시스템의 호스트에 대한 스토리지 유닛을 쉽고 빠르게 프로비저닝할 수 있습니다.

이 예에서는 VMware 호스트용 새 스토리지 유닛 6개를 생성합니다.

System Manager 메뉴에서 * Storage * 를 선택한 다음 * Add * 를 선택합니다.

스토리지 유닛의 이름, 유닛 수 및 각 유닛의 용량을 입력한 다음 호스트 운영 체제를 선택합니다.

두 개 이상의 유닛을 생성하는 경우 기본적으로 각 유닛은 동일한 용량으로 생성됩니다.

호스트 정보를 입력하려면 * 추가 옵션 * 을 선택하십시오. 이 예에서는 SCSI 프로토콜을 선택하고 새 iSCSI 호스트를 추가합니다.

호스트 이름을 입력한 다음 호스트 이니시에이터와 설명을 추가합니다.

스케줄 스냅샷 * 을 선택하여 일반 스냅샷으로 스토리지 유닛을 보호합니다.

원격 보호를 선택하여 장치를 원격 위치로 * 복제하십시오 *.

스토리지 VM 및 복제 정책을 선택하고 * Add * 를 선택합니다.

복제를 위해 스토리지 유닛이 정합성 보장 그룹에 있어야 합니다. 일관성 그룹 이름을 입력하고 * Create * 를 선택합니다.

로컬 및 원격 데이터 보호 기능을 갖춘 VMware 호스트용 스토리지 유닛 6개를 빠르고 쉽게 프로비저닝할 수 있습니다.
