---
sidebar: sidebar 
permalink: data-protection/manage-consistency-groups.html 
keywords: consistency groups, snapshots, data protection, protect data, add, remove, delete, storage units, lun, namespace, increase capacity 
summary: 정합성 보장 그룹을 사용하여 각 유닛에 대해 개별적으로 작업을 수행하는 대신 여러 스토리지 유닛에 대해 동시에 다양한 작업을 수행합니다. 
---
= ASA r2 스토리지 시스템의 ONTAP 일관성 그룹에 대해 알아보세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
일관성 그룹은 단일 단위로 관리되는 저장 단위의 모음입니다.  일관성 그룹을 사용하면 스토리지 관리가 간소화됩니다.

예를 들어, 일관성 그룹에 10개의 저장 장치로 구성된 데이터베이스가 있고 전체 데이터베이스를 백업해야 한다고 가정해 보겠습니다. 각 저장 장치를 백업하는 대신 일관성 그룹에 스냅샷 데이터 보호를 추가하기만 하면 전체 데이터베이스를 백업할 수 있습니다.  저장 장치를 개별적으로 백업하는 대신 일관성 그룹으로 백업하면 모든 장치에 대한 일관된 백업이 제공되지만, 장치를 개별적으로 백업하면 불일치가 발생할 가능성이 있습니다.

ONTAP 9.16.1부터 System Manager를 사용하여 ASA r2 시스템에서 계층적 일관성 그룹을 만들 수 있습니다.  계층적 구조에서는 하나 이상의 일관성 그룹이 부모 일관성 그룹 아래의 자식으로 구성됩니다.

계층적 정합성 보장 그룹을 사용하면 각 하위 정합성 보장 그룹에 개별 스냅샷 정책을 적용하고 상위 정합성 보장 그룹을 복제하여 모든 하위 정합성 보장 그룹의 스냅샷을 단일 유닛으로 원격 클러스터에 복제할 수 있습니다. 따라서 복잡한 데이터 구조에 대한 데이터 보호 및 관리가 간소화됩니다. 예를 들어, 애플리케이션 데이터와 `SVM1app_logs` 애플리케이션 로그라는 두 개의 하위 정합성 보장 그룹이 포함된 이라는 부모 정합성 보장 `SVM1app_data` 그룹을 생성한다고 `SVM1_app` 가정합니다. 의 스냅샷은 `SVM1app_data` 15분마다 생성되며, 의 스냅샷은 `SVM1app_logs` 매시간마다 생성됩니다. 부모 정합성 보장 그룹에는 `SVM1_app,` 및 `SVM1app_logs` 의 스냅샷을 24시간마다 원격 클러스터에 복제하는 SnapMirror 정책이 `SVM1app_data` 있습니다. 부모 정합성 보장 `SVM1_app` 그룹은 단일 유닛으로 관리되고 하위 정합성 보장 그룹은 별도의 유닛으로 관리됩니다.



== 복제 관계의 일관성 그룹

ONTAP 9.17.1부터 관계를 끊거나 삭제하지 않고도 비동기 복제 관계 또는 SnapMirror 활성 동기화 관계의 일관성 그룹에 다음과 같은 지오메트리 변경을 적용할 수 있습니다.  기본 일관성 그룹에서 기하학적 변경이 발생하면 변경 사항이 보조 일관성 그룹에 복제됩니다.

* link:manage-consistency-groups-add-remove-storage-units.html["저장 장치 크기 수정"]저장 장치를 추가하거나 제거하여.
* link:manage-hierarchical-consistency-groups.html#promote-an-existing-consistency-group-into-a-parent-consistency-group["단일 일관성 그룹을 홍보합니다."]부모 일관성 그룹에.
* link:manage-hierarchical-consistency-groups.html#demote-a-parent-consistency-group-to-a-single-consistency-group["부모 일관성 그룹 강등"]단일 일관성 그룹으로.
* link:manage-hierarchical-consistency-groups.html#detach-a-child-consistency-group-from-a-parent-consistency-group["자식 일관성 그룹 분리"]부모 일관성 그룹에서.
* link:manage-hierarchical-consistency-groups.html#create-a-child-consistency-group["하위 정합성 보장 그룹을 생성합니다"]기존 일관성 그룹을 사용합니다.


ONTAP 9.16.1에서는 다음을 수행해야 합니다.link:snapmirror-active-sync-break-relationship.html["비동기 복제 관계를 끊다"] 그리고link:snapmirror-active-sync-delete-relationship.html["SnapMirror 활성 동기화 관계 삭제"] 일관성 그룹에 기하학적 변경을 하기 전에.
