---
sidebar: sidebar 
permalink: data-protection/snapmirror-active-sync-confirm-cluster-configuration.html 
keywords: asa r2, data protection, business continuity, snapmirror active sync, cluster configuration 
summary: SnapMirror 액티브 싱크를 구성하기 전에 ASA r2 클러스터가 지원되는 피어링 관계에 있는지, 그리고 기타 구성 요구 사항을 충족하는지 확인해야 합니다. 
---
= SnapMirror Active Sync를 구성하기 전에 ASA r2 클러스터 구성을 확인하세요.
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror 액티브 싱크는 장애 조치 발생 시 데이터를 보호하기 위해 피어링된 클러스터를 사용합니다. SnapMirror 액티브 싱크를 구성하기 전에 ASA r2 클러스터가 지원되는 피어링 관계에 있는지, 그리고 기타 구성 요구 사항을 충족하는지 확인해야 합니다.

.단계
. 클러스터 간에 클러스터 피어링 관계가 있는지 확인합니다.
+

NOTE: SnapMirror Active Sync에서는 클러스터 피어 관계를 위해 기본 IP 공간이 필요합니다. 사용자 지정 IP 공간은 지원되지 않습니다.

+
link:snapshot-replication.html#step-1-create-a-cluster-peer-relationship["클러스터 피어 관계 생성"] .

. 각 클러스터의 스토리지 가상 머신(VM) 간에 피어 관계가 있는지 확인합니다.
+
link:create-svm-peer-relationship.html["클러스터 간 스토리지 VM 피어 관계 생성"] .

. 클러스터의 각 노드에 최소한 하나의 LIF가 생성되었는지 확인하세요.
+
link:../administer/manage-client-vm-access.html#create-a-lif-network-interface["LIF 생성"]

. 필요한 저장 장치가 생성되어 호스트 그룹에 매핑되었는지 확인합니다.
+
link:../manage-data/provision-san-storage.html#create-storage-units["저장 공간을 만드세요"] 그리고 link:../manage-data/provision-san-storage.html#map-the-storage-unit-to-a-host["저장 장치를 호스트 그룹에 매핑합니다."] .

. 새로운 저장 장치를 발견하려면 애플리케이션 호스트를 다시 검사하세요.


.다음 단계
클러스터 구성을 확인한 후에는 준비가 됩니다. link:install-ontap-mediator.html["ONTAP Mediator 설치"] .
